server:
  port: 9016

eureka:         #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      #defaultZone: ${EUREKA_URI:http://service-discovery:9019/eureka}
      defaultZone: ${EUREKA_URI:http://localhost:9019/eureka}
      healthcheck:
        enabled: true


spring:
  application:
    name: product-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: product-service_db
      port: 27017

